- name: Encode custom proxy settings as bind credentials
  asb_encode_binding:
    fields:
      http_proxy:  "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"
      no_proxy:    "{{ no_proxy }}"
      HTTP_PROXY:  "{{ http_proxy }}"
      HTTPS_PROXY: "{{ https_proxy }}"
      NO_PROXY:    "{{ no_proxy }}"
  when: _apb_plan_id == "custom"
    
- name: Encode broker proxy settings as bind credentials
  asb_encode_binding:
    fields:
      http_proxy:  "{{ lookup('env','http_proxy') }}"
      https_proxy: "{{ lookup('env','https_proxy') }}"
      no_proxy:    "{{ lookup('env','no_proxy') }}"
      HTTP_PROXY:  "{{ lookup('env','http_proxy') }}"
      HTTPS_PROXY: "{{ lookup('env','https_proxy') }}"
      NO_PROXY:    "{{ lookup('env','no_proxy') }}"
  when: _apb_plan_id == "passthrough"
